name: All Quality Checks

on:
  workflow_dispatch:

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml

  clippy:
    uses: ./.github/workflows/clippy.yml

  rustfmt:
    uses: ./.github/workflows/rustfmt.yml